name: Test Runner

on: [push, workflow_dispatch]

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Check OS
        run: uname -a
      - name: List files
        run: ls -la
      - name: Print env vars
        run: printenv 
      - name: Install unzip
        run: |
          apt-get update
          apt-get install -y unzip        
      - name: Setup AWS CLI
        if: always()
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          rm -rf awscliv2.zip aws/   
      - name: CheckAws
        if: always()
        run: aws --version
      - name: Verify AWS CLI
        run: ~/.local/bin/aws --version        
