name: Test Runner

on: [push, workflow_dispatch]

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Check OS
        run: uname -a
      - name: Check .NET version
        run: dotnet --version
      - name: List files
        run: ls -la
      - name: Print env vars
        run: printenv | grep GITHUB
