name: Test Runner

on: [push, workflow_dispatch]

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Check OS
        run: uname -a
      - name: List files
        run: ls -la
      - name: Print env vars
        run: printenv 
      - name: CheckDocker
        if: always()
        run: docker -v
      - name: Setup AWS CLI
        uses: aws-actions/setup-aws-cli@v1      
      - name: CheckAws
        if: always()
        run: aws --version
      - name: Verify AWS CLI
        run: ~/.local/bin/aws --version        
